"""
Autonomous Brain Module.

This file is responsible for:
- Implementing the central autonomous orchestrator for the job-hunting agent.
- Executing the real cognitive feedback loop:
  OBSERVE -> DIAGNOSE -> DECIDE -> ACT -> REFLECT -> REPEAT or STOP.
- Managing run isolation using unique run_id.
- Maintaining intra-run deduplication to allow lifecycle revalidation across runs.
- Collecting deterministic execution statistics and granular rejection reasons.
- Executing actions through the strict pipeline:
  Search -> Normalize -> Deduplicate -> Posting Age Filter -> Availability Verification -> Hard Filters -> LLM Evaluation.
- Enforcing latest-first sorting (newest posting age first, secondary by score).
- Persisting run-isolated historical outputs and updating latest output.
- Halting strictly upon reaching target job count, maximum iterations, or exhausting viable strategies.
"""

import json
from typing import Any, Dict, List, Optional, Set, Tuple
from config.settings import settings
from agent.evaluator import JobEvaluator
from agent.tools.memory import MemoryTool
from pydantic import BaseModel, Field
from agent.tools.results import ResultsTool
from agent.tools.search_jobs import SearchJobsTool
from infrastructure.ollama import OllamaClient
from models.candidate import CandidateProfile
from models.evaluation import JobEvaluation
from models.job import Job
from models.mission import SearchMission
from pipeline.availability import JobAvailabilityVerifier
from pipeline.deduplicator import JobDeduplicator
from pipeline.filters import HardFilterEngine
from pipeline.normalizer import JobNormalizer
from utils.logger import get_logger, generate_run_id

logger = get_logger("agent.brain")


class QueryStrategy(BaseModel):
    """Structured search query and strategic rationale generated by the LLM."""
    query: str = Field(..., description="SearXNG search query string targeting job discovery")
    rationale: str = Field(..., description="Strategic explanation for this query choice based on diagnosis")


class BrainDecision:
    """Represents a decided action for the upcoming iteration."""
    def __init__(self, action: str, query: str, rationale: str) -> None:
        self.action = action        # "search" or "stop"
        self.query = query          # query to execute if action is "search"
        self.rationale = rationale  # explanation of why this action was decided


class AutonomousBrain:
    """
    Central orchestrator controlling state, memory, tools, and the cognitive feedback loop.
    """

    def __init__(
        self,
        candidate: CandidateProfile,
        mission: SearchMission,
        search_tool: Optional[SearchJobsTool] = None,
        memory_tool: Optional[MemoryTool] = None,
        results_tool: Optional[ResultsTool] = None,
        evaluator: Optional[JobEvaluator] = None,
        ollama_client: Optional[OllamaClient] = None,
        availability_verifier: Optional[JobAvailabilityVerifier] = None,
        run_id: Optional[str] = None,
        search_prompt: Optional[str] = None
    ) -> None:
        self.candidate = candidate
        self.mission = mission
        self.run_id = run_id or generate_run_id()
        self.search_prompt = search_prompt

        # Agent tools
        self.search_tool = search_tool or SearchJobsTool()
        self.memory_tool = memory_tool or MemoryTool()
        self.results_tool = results_tool or ResultsTool()
        self.evaluator = evaluator or JobEvaluator(ollama_client)
        self.ollama = ollama_client or OllamaClient()

        # Pipeline components: Intra-run deduplicator allows lifecycle revalidation across runs
        self.normalizer = JobNormalizer()
        self.deduplicator = JobDeduplicator()
        self.filter_engine = HardFilterEngine()
        self.availability_verifier = availability_verifier or JobAvailabilityVerifier()

        # Internal execution state
        self.accepted_jobs: List[Job] = []
        self.evaluations: Dict[str, JobEvaluation] = {}
        self.iteration: int = 0
        self.is_stopped: bool = False

        # Deterministic per-run statistics tracking
        self.run_statistics: Dict[str, int] = {
            "discovered": 0,
            "unique": 0,
            "stale": 0,
            "fresh": 0,
            "availability_checked": 0,
            "active": 0,
            "closed": 0,
            "expired": 0,
            "removed": 0,
            "unknown": 0,
            "hard_filter_passed": 0,
            "llm_evaluated": 0,
            "accepted": 0,
            "rejected": 0
        }

        # Granular rejection log
        self.run_rejections: List[Dict[str, Any]] = []

        # State tracking between iterations
        self.last_observation: Dict[str, Any] = {
            "iteration": 0,
            "query": "",
            "raw_count": 0,
            "duplicate_count": 0,
            "filter_rejected_count": 0,
            "evaluated_count": 0,
            "accepted_count": 0,
            "low_score_count": 0,
            "dominant_rejection_reason": None
        }

    # -------------------------------------------------------------------------
    # 1. OBSERVE
    # -------------------------------------------------------------------------
    def observe(self) -> Dict[str, Any]:
        """
        Inspects the outcome of previous actions, current memory state, and progress toward goals.
        """
        current_accepted = len(self.accepted_jobs)
        target = self.mission.minimum_target_jobs
        previously_searched = self.memory_tool.get_searched_queries()

        observation = {
            "run_id": self.run_id,
            "current_iteration": self.iteration,
            "max_iterations": self.mission.max_iterations,
            "accepted_jobs_count": current_accepted,
            "target_job_count": target,
            "max_posting_age_days": self.mission.posting_age_days,
            "progress_pct": round((current_accepted / target) * 100, 1) if target > 0 else 100.0,
            "total_queries_searched": len(previously_searched),
            "last_iteration_stats": self.last_observation
        }

        logger.info(
            f"[OBSERVE] Iteration {self.iteration}/{self.mission.max_iterations} | "
            f"Accepted: {current_accepted}/{target} ({observation['progress_pct']}%) | "
            f"Max Age: {self.mission.posting_age_days}d"
        )
        return observation

    # -------------------------------------------------------------------------
    # 2. DIAGNOSE
    # -------------------------------------------------------------------------
    def diagnose(self, observation: Dict[str, Any]) -> str:
        """
        Analyzes the observed metrics to identify systemic patterns:
        - Freshness/availability friction (stale results or closed jobs)
        - Query saturation / high duplicate rate
        - Low search yield (query too restrictive)
        - Location mismatch
        - Experience or semantic mismatch
        """
        # Case 1: First iteration
        if self.iteration == 0:
            diagnosis = (
                f"Initial cycle: Establish baseline search using primary role and core skills "
                f"targeting jobs posted within {self.mission.posting_age_days} days."
            )
            logger.info(f"[DIAGNOSE] {diagnosis}")
            return diagnosis

        # Case 2: Target quota already fulfilled
        if observation["accepted_jobs_count"] >= observation["target_job_count"]:
            diagnosis = f"Target reached: Successfully accepted {observation['accepted_jobs_count']} matching positions."
            logger.info(f"[DIAGNOSE] {diagnosis}")
            return diagnosis

        last_stats = observation["last_iteration_stats"]
        raw_count = last_stats.get("raw_count", 0)
        dup_count = last_stats.get("duplicate_count", 0)
        filter_rej = last_stats.get("filter_rejected_count", 0)
        eval_count = last_stats.get("evaluated_count", 0)
        accepted_last = last_stats.get("accepted_count", 0)
        dominant_rej = str(last_stats.get("dominant_rejection_reason", ""))

        # Case 3: Freshness / Availability friction
        if raw_count > 0 and (filter_rej / raw_count) > 0.4 and (
            "posting age" in dominant_rej.lower() or "availability" in dominant_rej.lower()
        ):
            diagnosis = (
                f"Freshness/availability friction ({filter_rej} rejected): Primary cause was '{dominant_rej}'. "
                f"Search engines returned outdated or closed postings. Adapting search strategy with fresh "
                f"keywords or alternative role phrasing without relaxing the {self.mission.posting_age_days}-day limit."
            )
            logger.info(f"[DIAGNOSE] {diagnosis}")
            return diagnosis

        # Case 4: Zero or extremely low search yield
        if raw_count < 3:
            diagnosis = (
                f"Low search yield ({raw_count} results): Query was too specific or search terms too constrained. "
                "Need to broaden role terminology and remove secondary keyword filters."
            )
            logger.info(f"[DIAGNOSE] {diagnosis}")
            return diagnosis

        # Case 5: Severe duplicate saturation
        if raw_count > 0 and (dup_count / raw_count) > 0.6:
            diagnosis = (
                f"Query saturation ({dup_count}/{raw_count} duplicates): This search angle has been exhausted. "
                "Need to pivot to alternative role titles, different geographic combinations, or orthogonal skill clusters."
            )
            logger.info(f"[DIAGNOSE] {diagnosis}")
            return diagnosis

        # Case 6: High hard-filter rejection (locations, companies, work modes)
        if raw_count > 0 and (filter_rej / raw_count) > 0.5:
            diagnosis = (
                f"Deterministic filter friction ({filter_rej} rejected): Primary cause was {dominant_rej}. "
                "Need to sharpen location or company targeting."
            )
            logger.info(f"[DIAGNOSE] {diagnosis}")
            return diagnosis

        # Case 7: High semantic evaluation rejection
        if eval_count > 0 and accepted_last == 0:
            diagnosis = (
                f"Semantic mismatch ({eval_count} evaluated, 0 accepted): Jobs returned do not match candidate experience "
                "level or core stack. Need to adjust seniority qualifiers (e.g. junior/mid) and re-align core skills."
            )
            logger.info(f"[DIAGNOSE] {diagnosis}")
            return diagnosis

        # Case 8: Productive search
        diagnosis = (
            f"Effective search ({accepted_last} accepted): Current strategy is viable. "
            "Broaden to adjacent role variations or next location target to keep momentum."
        )
        logger.info(f"[DIAGNOSE] {diagnosis}")
        return diagnosis

    # -------------------------------------------------------------------------
    # 3. DECIDE
    # -------------------------------------------------------------------------
    def decide(self, observation: Dict[str, Any], diagnosis: str) -> BrainDecision:
        """
        Determines the next action and formulates an adapted search query based on diagnosis.
        Never relaxes the candidate's max_posting_age_days constraint.
        """
        # Check stopping conditions first
        if observation["accepted_jobs_count"] >= observation["target_job_count"]:
            return BrainDecision(
                action="stop",
                query="",
                rationale="Target job quota satisfied."
            )

        if self.iteration >= self.mission.max_iterations:
            return BrainDecision(
                action="stop",
                query="",
                rationale=f"Maximum allowed iterations ({self.mission.max_iterations}) reached."
            )

        # Formulate query using LLM reasoning with fallback
        searched_queries = self.memory_tool.get_searched_queries()
        query, rationale = self._generate_adapted_query(diagnosis, searched_queries)

        if not query or self.memory_tool.memory.is_query_searched(query):
            # Fallback heuristic query mutation if query was already used
            query, rationale = self._generate_heuristic_query(self.iteration, searched_queries)

        logger.info(f"[DECIDE] Decision: Search with query '{query}' | Rationale: {rationale}")
        return BrainDecision(action="search", query=query, rationale=rationale)

    def _generate_adapted_query(self, diagnosis: str, searched_queries: List[str]) -> Tuple[str, str]:
        """
        Asks the local LLM to reason about the diagnosis and synthesize an adapted search query.
        """
        system_prompt = (
            "You are the reasoning strategist for an autonomous job search agent.\n"
            "Analyze the candidate profile, previous searched queries, and the current diagnosis.\n"
            "Formulate a NEW search query specifically formatted for LinkedIn discovery via search engines.\n"
            "Format queries like: site:linkedin.com/jobs/view \"Role Title\" Location Keyword\n"
            "Rules:\n"
            "1. Do NOT repeat any previously searched query.\n"
            "2. Adapt based on the diagnosis (broaden if yield was low, change keywords if duplicates high, "
            "add seniority markers if experience mismatched).\n"
            f"3. The candidate has a strict hard freshness constraint of {self.mission.posting_age_days} days. "
            "NEVER attempt to relax or broaden the posting age limit.\n"
            "4. Output valid JSON conforming to the QueryStrategy schema."
        )

        user_prompt = (
            f"CANDIDATE:\n"
            f"- Target Roles: {self.candidate.target_roles}\n"
            f"- Skills: {self.candidate.skills}\n"
            f"- Experience: {self.candidate.experience_years} years\n"
            f"- Locations: {self.candidate.locations}\n"
            f"- Max Posting Age: {self.mission.posting_age_days} days (HARD CONSTRAINT)\n\n"
            f"PREVIOUS QUERIES ALREADY SEARCHED:\n{searched_queries}\n\n"
            f"CURRENT DIAGNOSIS:\n{diagnosis}\n\n"
            "Formulate an adapted LinkedIn search query and strategic rationale conforming to the QueryStrategy schema."
        )

        try:
            strategy = self.ollama.generate_structured(
                prompt=user_prompt,
                schema=QueryStrategy,
                system=system_prompt,
                max_retries=2
            )
            candidate_query = strategy.query.strip()
            rationale = strategy.rationale.strip()

            # Validate that query begins with or includes site:linkedin.com
            if candidate_query and not candidate_query.startswith("site:linkedin.com"):
                candidate_query = f"site:linkedin.com/jobs/view {candidate_query}"

            return candidate_query, rationale

        except Exception as e:
            logger.warning(f"LLM query adaptation failed ({e}). Falling back to heuristic strategy.")
            return self._generate_heuristic_query(self.iteration, searched_queries)

    def _generate_heuristic_query(self, iteration_idx: int, searched_queries: List[str]) -> Tuple[str, str]:
        """
        Deterministic strategy generator ensuring unique queries across iterations.
        """
        roles = self.candidate.target_roles
        skills = self.candidate.skills
        locations = self.candidate.locations or [""]

        # Cycle through role, location, and skill permutations
        role = roles[iteration_idx % len(roles)]
        location = locations[iteration_idx % len(locations)] if locations else ""

        if iteration_idx == 0:
            selected_skills = skills[:2]
            rationale = f"Baseline search focusing on primary role '{role}' and core skills {selected_skills}."
        elif iteration_idx == 1:
            selected_skills = skills[1:3] if len(skills) > 2 else skills[:1]
            rationale = f"Pivoting to secondary skill set {selected_skills} for role '{role}'."
        elif iteration_idx == 2:
            selected_skills = []
            rationale = f"Broadening query by searching role '{role}' in location '{location}' without skill restrictions."
        else:
            exp_term = "senior" if self.candidate.experience_years >= 5 else "mid junior"
            selected_skills = skills[:1]
            rationale = f"Refining search with experience qualifier '{exp_term}' for '{role}'."

        parts = ["site:linkedin.com/jobs/view", f'"{role}"']
        if location:
            parts.append(f'"{location}"')
        for s in selected_skills:
            parts.append(s)

        query = " ".join(parts)

        # If already searched, append variation
        if query in searched_queries:
            query = f"{query} remote"
            rationale += " Appending 'remote' to ensure query novelty."

        return query, rationale

    # -------------------------------------------------------------------------
    # 4. ACT
    # -------------------------------------------------------------------------
    def act(self, decision: BrainDecision) -> Dict[str, Any]:
        """
        Executes search through the strict pipeline:
        Search -> Normalize -> Deduplicate -> Posting Age Filter -> Availability Verification -> Hard Filters -> LLM Evaluation.
        Collects deterministic execution statistics and granular rejection reasons.
        """
        query = decision.query
        logger.info(f"[ACT] Executing search query: '{query}'")

        # 1. Record query in memory
        self.memory_tool.memory.record_query(query, success=True)

        # 2. Search via tool
        raw_jobs = self.search_tool.execute(
            query=query,
            allowed_providers=self.mission.allowed_providers
        )
        raw_count = len(raw_jobs)
        self.run_statistics["discovered"] += raw_count

        if raw_count == 0:
            logger.warning(f"[ACT] Query '{query}' yielded zero results.")
            self.memory_tool.memory.failed_queries.append(query)
            return {
                "raw_count": 0,
                "duplicate_count": 0,
                "filter_rejected_count": 0,
                "evaluated_count": 0,
                "accepted_count": 0,
                "dominant_rejection_reason": "No search results returned"
            }

        # 3. Normalize (Cleans text, extracts posting age and date confidence)
        normalized_jobs = self.normalizer.normalize_batch(raw_jobs)

        # 4. Deduplicate (Intra-run deduplication)
        unique_jobs, duplicate_count = self.deduplicator.deduplicate(normalized_jobs)
        self.run_statistics["unique"] += len(unique_jobs)

        # Record intra-run duplicates in rejection log
        seen_set = set(j.url for j in unique_jobs)
        for job in normalized_jobs:
            if job.url not in seen_set:
                self.run_rejections.append({
                    "job_url": job.url,
                    "title": job.title,
                    "company": job.company,
                    "stage": "deduplication",
                    "reason": "duplicate",
                    "details": {}
                })

        # 5. Posting Age Filter (Deterministic check before network verification)
        fresh_jobs: List[Job] = []
        age_rejected: List[Tuple[Job, str]] = []
        for job in unique_jobs:
            age_ok, age_reason = HardFilterEngine.matches_posting_age(job, self.mission.posting_age_days)
            if age_ok:
                fresh_jobs.append(job)
                self.run_statistics["fresh"] += 1
            else:
                self.run_statistics["stale"] += 1
                logger.info(f"[ACT] Freshness filter rejected '{job.title}' ({job.url}): {age_reason}")
                age_rejected.append((job, age_reason or "Exceeded max posting age"))
                self.memory_tool.memory.record_job_outcome(job.url, accepted=False, reason=age_reason)
                self.run_rejections.append({
                    "job_url": job.url,
                    "title": job.title,
                    "company": job.company,
                    "stage": "freshness",
                    "reason": "posting_age_exceeded" if job.posted_age_days is not None else "unknown_posting_age",
                    "details": {
                        "posted_age_days": job.posted_age_days,
                        "max_allowed_days": self.mission.posting_age_days,
                        "confidence": job.posting_date_confidence
                    }
                })

        # 6. Availability Verification (Probes remaining fresh jobs)
        self.run_statistics["availability_checked"] += len(fresh_jobs)
        verified_jobs = self.availability_verifier.verify_batch(fresh_jobs)

        # Track availability counts and rejections
        for job in verified_jobs:
            status_lower = job.availability_status.lower()
            if status_lower in self.run_statistics:
                self.run_statistics[status_lower] += 1

            if job.availability_status != "ACTIVE":
                self.run_rejections.append({
                    "job_url": job.url,
                    "title": job.title,
                    "company": job.company,
                    "stage": "availability",
                    "reason": f"job_{status_lower}",
                    "details": {
                        "availability_status": job.availability_status,
                        "checked_at": job.availability_checked_at
                    }
                })

        # 7. Apply Remaining Hard Filters (availability, excluded companies, locations, work modes)
        passed_jobs, filter_rejected = self.filter_engine.filter_batch(
            verified_jobs,
            self.mission
        )
        self.run_statistics["hard_filter_passed"] += len(passed_jobs)

        for r_job, r_reason in filter_rejected:
            # Avoid duplicate rejection logging if already logged in availability
            if "availability" not in r_reason.lower():
                self.run_rejections.append({
                    "job_url": r_job.url,
                    "title": r_job.title,
                    "company": r_job.company,
                    "stage": "hard_filter",
                    "reason": r_reason,
                    "details": {}
                })

        all_rejections = age_rejected + filter_rejected
        filter_rejected_count = len(all_rejections)

        dominant_reason = None
        if all_rejections:
            dominant_reason = all_rejections[0][1]

        # 8. Evaluate Passed Jobs via LLM (only fresh, available, valid jobs reach here)
        accepted_count = 0
        low_score_count = 0
        target = self.mission.minimum_target_jobs
        self.run_statistics["llm_evaluated"] += len(passed_jobs)

        for job in passed_jobs:
            # Check if we reached target mid-batch
            if len(self.accepted_jobs) >= target:
                logger.info(f"[ACT] Target job count of {target} reached during evaluation batch.")
                break

            evaluation = self.evaluator.evaluate(
                candidate=self.candidate,
                job=job,
                threshold=self.mission.evaluation_threshold
            )

            if evaluation.suitable:
                self.accepted_jobs.append(job)
                self.evaluations[job.url] = evaluation
                self.memory_tool.memory.record_job_outcome(job.url, accepted=True)
                accepted_count += 1
                self.run_statistics["accepted"] += 1
                logger.info(
                    f"[ACT] Job ACCEPTED: '{job.title}' at '{job.company}' "
                    f"(Score: {evaluation.score}, Age: {job.posted_age_days}d)"
                )
            else:
                self.memory_tool.memory.record_job_outcome(
                    job.url,
                    accepted=False,
                    reason=f"Low score ({evaluation.score})"
                )
                low_score_count += 1
                self.run_statistics["rejected"] += 1
                logger.info(f"[ACT] Job REJECTED: '{job.title}' at '{job.company}' (Score: {evaluation.score})")
                self.run_rejections.append({
                    "job_url": job.url,
                    "title": job.title,
                    "company": job.company,
                    "stage": "evaluation",
                    "reason": "llm_not_suitable",
                    "details": {
                        "score": evaluation.score,
                        "threshold": self.mission.evaluation_threshold,
                        "reasons": evaluation.reasons,
                        "missing_skills": evaluation.missing_skills
                    }
                })

        iteration_metrics = {
            "query": query,
            "raw_count": raw_count,
            "duplicate_count": duplicate_count,
            "filter_rejected_count": filter_rejected_count,
            "evaluated_count": len(passed_jobs),
            "accepted_count": accepted_count,
            "low_score_count": low_score_count,
            "dominant_rejection_reason": dominant_reason
        }
        return iteration_metrics

    # -------------------------------------------------------------------------
    # 5. REFLECT
    # -------------------------------------------------------------------------
    def reflect(self, observation: Dict[str, Any], diagnosis: str, decision: BrainDecision, metrics: Dict[str, Any]) -> None:
        """
        Records the cycle outcome, updates memory persistence, and prepares next state.
        """
        self.last_observation = metrics
        self.iteration += 1
        self.memory_tool.memory.iteration = self.iteration

        # Record cycle in audit trail
        self.memory_tool.memory.record_cycle(
            observation=observation,
            diagnosis=diagnosis,
            decision=f"{decision.action}: {decision.query} ({decision.rationale})"
        )

        # Persist memory to sandbox/memory/agent_memory.json
        self.memory_tool.save()

        logger.info(
            f"[REFLECT] Finished cycle {self.iteration}. Cumulative accepted jobs: "
            f"{len(self.accepted_jobs)}/{self.mission.minimum_target_jobs}"
        )

    # -------------------------------------------------------------------------
    # Central Loop: OBSERVE -> DIAGNOSE -> DECIDE -> ACT -> REFLECT
    # -------------------------------------------------------------------------
    def run(self) -> List[Job]:
        """
        Executes the Autonomous Brain control loop until a stopping condition is met.
        Enforces latest-first sorting and run-isolated persistence.
        Returns the list of accepted jobs.
        """
        logger.info(
            f"=== Starting Autonomous Brain Loop [{self.run_id}] | Objective: '{self.mission.objective}' "
            f"| Max Age: {self.mission.posting_age_days}d ==="
        )

        while not self.is_stopped:
            # 1. OBSERVE
            observation = self.observe()

            # 2. DIAGNOSE
            diagnosis = self.diagnose(observation)

            # 3. DECIDE
            decision = self.decide(observation, diagnosis)

            if decision.action == "stop":
                logger.info(f"=== Stopping condition reached: {decision.rationale} ===")
                self.is_stopped = True
                break

            # 4. ACT
            metrics = self.act(decision)

            # 5. REFLECT
            self.reflect(observation, diagnosis, decision, metrics)

            # Check if target reached after reflection
            if len(self.accepted_jobs) >= self.mission.minimum_target_jobs:
                logger.info(f"=== Target job count satisfied ({len(self.accepted_jobs)} accepted) ===")
                self.is_stopped = True
                break

        # Deterministic Sorting: Latest jobs first (posted_age_days ASC, secondary evaluation.score DESC)
        self.accepted_jobs.sort(
            key=lambda j: (
                j.posted_age_days if j.posted_age_days is not None else 999999,
                -(self.evaluations[j.url].score if j.url in self.evaluations and self.evaluations[j.url] else 0)
            )
        )

        # Persist run results: writes sandbox/output/runs/<run_id>/jobs.json AND sandbox/output/jobs.json
        self.results_tool.save_run_results(
            run_id=self.run_id,
            mission=self.mission,
            accepted_jobs=self.accepted_jobs,
            evaluations=self.evaluations,
            customer_id=self.candidate.customer_id,
            search_prompt=self.search_prompt
        )

        # Persist deterministic run summary: sandbox/output/runs/<run_id>/summary.json
        self.results_tool.save_run_summary(
            run_id=self.run_id,
            statistics=self.run_statistics,
            rejections=self.run_rejections,
            customer_id=self.candidate.customer_id,
            search_prompt=self.search_prompt
        )

        logger.info(
            f"=== Autonomous Brain completed [{self.run_id}]. "
            f"Accepted: {len(self.accepted_jobs)} jobs | Total discovered: {self.run_statistics['discovered']} ==="
        )
        return self.accepted_jobs
